<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $properties = [
            [
                'title' => 'Rumah Modern Jababeka',
                'description' => 'Rumah modern dengan fasilitas lengkap di kawasan Jababeka, Cikarang. Lokasi strategis dekat dengan kawasan industri.',
                'price' => 350000000,
                'location' => 'Cikarang',
                'sub_location' => 'Jababeka',
                'type' => 'rumah',
                'status' => 'dijual',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 130,
                'land_area' => 150,
                'floors' => 1,
                'images' => json_encode(['/images/p1.png']),
                'features' => json_encode(['Carport', 'Taman', 'Air PAM']),
                'whatsapp_number' => '6281234567890',
                'financing' => 'KPR tersedia dengan DP 10%',
            ],
            [
                'title' => 'Ruko 3 Lantai Lippo Cikarang',
                'description' => 'Ruko strategis di pusat bisnis Lippo Cikarang. Cocok untuk usaha retail atau kantor.',
                'price' => 1500000000,
                'location' => 'Cikarang',
                'sub_location' => 'Lippo Cikarang',
                'type' => 'ruko',
                'status' => 'dijual',
                'bedrooms' => 0,
                'bathrooms' => 3,
                'area' => 200,
                'land_area' => 120,
                'floors' => 3,
                'images' => json_encode(['/images/p2.png']),
                'features' => json_encode(['Parkir Luas', 'Lokasi Strategis', 'AC']),
                'whatsapp_number' => '6281234567891',
                'financing' => 'Cash keras atau KPR dengan DP 30%',
            ],
            [
                'title' => 'Rumah Minimalis Bekasi Timur',
                'description' => 'Rumah minimalis modern di kawasan Bekasi Timur yang berkembang pesat.',
                'price' => 450000000,
                'location' => 'Bekasi',
                'sub_location' => 'Bekasi Timur',
                'type' => 'rumah',
                'status' => 'dijual',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 80,
                'land_area' => 120,
                'floors' => 2,
                'images' => json_encode(['/images/p3.png']),
                'features' => json_encode(['Garasi', 'Taman Belakang', 'Smart Home']),
                'whatsapp_number' => '6281234567892',
                'financing' => 'KPR tersedia dengan berbagai bank',
            ],
            [
                'title' => 'Apartemen Grand Galaxy City',
                'description' => 'Apartemen furnished di Grand Galaxy City dengan view kota yang menawan.',
                'price' => 400000000,
                'location' => 'Bekasi',
                'sub_location' => 'Grand Galaxy',
                'type' => 'apartemen',
                'status' => 'dijual',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area' => 36,
                'land_area' => 0,
                'floors' => 1,
                'images' => json_encode(['/images/p4.png']),
                'features' => json_encode(['Furnished', 'Swimming Pool', 'Security 24/7', 'Gym']),
                'whatsapp_number' => '6281234567893',
                'financing' => 'Cash atau KPR tersedia',
            ],
            [
                'title' => 'Rumah Mewah Pondok Indah',
                'description' => 'Rumah mewah dengan desain eksklusif di kawasan elite Pondok Indah, Jakarta Selatan.',
                'price' => 8500000000,
                'location' => 'Jakarta',
                'sub_location' => 'Pondok Indah',
                'type' => 'rumah',
                'status' => 'dijual',
                'bedrooms' => 5,
                'bathrooms' => 4,
                'area' => 400,
                'land_area' => 500,
                'floors' => 2,
                'images' => json_encode(['/images/p5.png']),
                'features' => json_encode(['Private Pool', 'Smart Home', 'Home Theater', 'Wine Cellar']),
                'whatsapp_number' => '6281234567894',
                'ig_url' => 'https://instagram.com/adaproperty',
                'tiktok_url' => 'https://tiktok.com/@adaproperty',
                'financing' => 'Cash keras preferred',
            ],
            [
                'title' => 'Kavling Siap Bangun Karawang',
                'description' => 'Kavling strategis dekat akses tol Karawang, cocok untuk investasi atau dibangun rumah.',
                'price' => 250000000,
                'location' => 'Karawang',
                'sub_location' => 'Karawang Barat',
                'type' => 'kavling',
                'status' => 'dijual',
                'bedrooms' => 0,
                'bathrooms' => 0,
                'area' => 0,
                'land_area' => 200,
                'floors' => 0,
                'images' => json_encode(['/images/p6.png']),
                'features' => json_encode(['Sertifikat SHM', 'Akses Jalan Lebar', 'Dekat Tol']),
                'whatsapp_number' => '6281234567895',
                'financing' => 'Cash bertahap atau KPR tanah',
            ],
            [
                'title' => 'Gudang Industri Jababeka',
                'description' => 'Gudang luas dengan fasilitas loading dock di kawasan industri Jababeka.',
                'price' => 3500000000,
                'location' => 'Cikarang',
                'sub_location' => 'Jababeka',
                'type' => 'gudang',
                'status' => 'dijual',
                'bedrooms' => 0,
                'bathrooms' => 2,
                'area' => 800,
                'land_area' => 1000,
                'floors' => 1,
                'images' => json_encode(['/images/p7.png']),
                'features' => json_encode(['Loading Dock', 'Parkir Truk', 'Security', 'Listrik 3 Phase']),
                'whatsapp_number' => '6281234567896',
                'financing' => 'Cash atau kredit bank corporate',
            ],
            [
                'title' => 'Rumah Cluster Bandung Utara',
                'description' => 'Rumah dalam cluster modern dengan fasilitas lengkap di Bandung Utara.',
                'price' => 850000000,
                'location' => 'Bandung',
                'sub_location' => 'Bandung Utara',
                'type' => 'rumah',
                'status' => 'dijual',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 120,
                'land_area' => 150,
                'floors' => 2,
                'images' => json_encode(['/images/p8.png']),
                'features' => json_encode(['Cluster Security', 'Playground', 'Jogging Track']),
                'whatsapp_number' => '6281234567897',
                'financing' => 'KPR tersedia dengan DP 20%',
            ],
            [
                'title' => 'Ruko Dijual Cepat Karawang',
                'description' => 'Ruko di lokasi ramai Karawang, cocok untuk berbagai jenis usaha.',
                'price' => 950000000,
                'location' => 'Karawang',
                'sub_location' => 'Karawang Timur',
                'type' => 'ruko',
                'status' => 'dijual',
                'bedrooms' => 1,
                'bathrooms' => 2,
                'area' => 150,
                'land_area' => 100,
                'floors' => 2,
                'images' => json_encode(['/images/p9.png']),
                'features' => json_encode(['Parkir Depan', 'Listrik Besar', 'Lokasi Ramai']),
                'whatsapp_number' => '6281234567898',
                'financing' => 'Nego sampai deal',
            ],
            [
                'title' => 'Rumah Disewakan Bekasi',
                'description' => 'Rumah siap huni untuk disewakan di kawasan Bekasi Barat.',
                'price' => 25000000,
                'location' => 'Bekasi',
                'sub_location' => 'Bekasi Barat',
                'type' => 'rumah',
                'status' => 'disewakan',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 100,
                'land_area' => 120,
                'floors' => 1,
                'images' => json_encode(['/images/p10.png']),
                'features' => json_encode(['Furnished', 'AC', 'Water Heater']),
                'whatsapp_number' => '6281234567899',
                'financing' => 'Sewa tahunan, bayar 2 tahun dapat diskon',
            ],
            [
                'title' => 'Pabrik Dijual di EJIP Cikarang',
                'description' => 'Pabrik lengkap dengan mesin produksi di kawasan EJIP Cikarang.',
                'price' => 15000000000,
                'location' => 'Cikarang',
                'sub_location' => 'EJIP',
                'type' => 'pabrik',
                'status' => 'dijual',
                'bedrooms' => 0,
                'bathrooms' => 4,
                'area' => 2000,
                'land_area' => 3000,
                'floors' => 1,
                'images' => json_encode(['/images/p11.png']),
                'features' => json_encode(['Mesin Lengkap', 'Genset', 'Office Area', 'Canteen']),
                'whatsapp_number' => '6281234567800',
                'financing' => 'Cash atau kredit bank dengan jaminan aset',
            ],
            [
                'title' => 'Apartemen Kemang Village Jakarta',
                'description' => 'Apartemen mewah fully furnished di Kemang Village dengan fasilitas premium.',
                'price' => 2500000000,
                'location' => 'Jakarta',
                'sub_location' => 'Kemang',
                'type' => 'apartemen',
                'status' => 'dijual',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 120,
                'land_area' => 0,
                'floors' => 1,
                'images' => json_encode(['/images/p12.png']),
                'features' => json_encode(['Fully Furnished', 'Sky Garden', 'Concierge', 'Premium Location']),
                'whatsapp_number' => '6281234567801',
                'tour_url' => 'https://example.com/virtual-tour',
                'financing' => 'Cash atau KPR',
            ],
        ];

        foreach ($properties as $property) {
            Property::create($property);
        }
    }
}
